# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
checkpoint_path: './checkpoint/'
checkpoint_file: './checkpoint/mask_rcnn-12_7393.ckpt'
device_target: Ascend
enable_profiling: False

pre_trained: "/cache/data"
coco_root: "/cache/data"
ckpt_path: ""

# static
below_low_threshold: -1
between_thresholds: -2

# ==============================================================================

# dataset
datasets_root: "/home/tiantian/Documents/internship/MindSpore/OCR/MaskTextSpotterV3/datasets"
datasets_name:
- "icdar2013"
- "icdar2015"
# - "synthtext"
# - "total_text"
- "scut-eng-char"

# icdar_2013_train: "icdar2013/train_images", "icdar2013/train_gts"
# icdar_2013_test: "icdar2013/test_images", "icdar2013/test_gts"
# icdar_2015_train: ("icdar2015/train_images", "icdar2015/train_gts")
# icdar_2015_test: ("icdar2015/test_images", "icdar2015/test_gts")
# synthtext_train: ("synthtext/train_images", "synthtext/train_gts")
# synthtext_test: ("synthtext/test_images", "synthtext/test_gts")
# total_text_train: ("total_text/train_images", "total_text/train_gts")
# total_text_test: ("total_text/test_images", "total_text/test_gts")
# scut-eng-char_train: ("scut-eng-char/train_images", "scut-eng-char/train_gts")

mindrecord_dir: "./mindrecords"
data_workers: 4
batch_size: 2

img_path: ''
result_path: ''

feature_shapes:
- [192, 320]
- [96, 160]
- [48, 80]
- [24, 40]
- [12, 20]

# Training options
img_width: 1280
img_height: 768
keep_ratio: True
flip_ratio: 0.5
expand_ratio: 1.0

max_instance_count: 128
mask_shape: [28, 28]

# resnet
resnet_block: [3, 4, 6, 3]
resnet_in_channels: [64, 256, 512, 1024]
resnet_out_channels: [256, 512, 1024, 2048]

# fpn
fpn_in_channels: [256, 512, 1024, 2048]
fpn_out_channels: 256
fpn_num_outs: 5

# Segmentation (Proposal)
binary_thresh: 0.5
box_thresh: 0.7
min_size: 0
top_n_train: 1000
top_n_test: 1000
expand_rate: 0.4

# roi
roi:
  box_head:
    resolution: 7
    scales: (0.25,)
    sample_rate: 2
    mlp_dim: 1024
    soft_mask_feat_rate: 0
    class_count: 2
  mask_head:
    resolution_h: 32
    resolution_w: 32
    scales: (0.25,)
    sample_rate: 2
    conv_layers: (256, 256, 256, 256)
    soft_mask_feat_rate: 0
    batch_size: 64
    char_class_count: 37


# seq
sequence:
  resize_w: 64
  resize_h: 16
  char_count: 38
  bos_token: 0
  ratio: 0
  max_len: 38

# bbox_assign_sampler
neg_iou_thr: 0.3
pos_iou_thr: 0.7
min_pos_iou: 0.3
num_bboxes: 245520
num_gts: 128
num_expected_neg: 256
num_expected_pos: 128

# proposal
activate_num_classes: 2
use_sigmoid_cls: True

